version: '2'

services:
  nginx:
    build: openresty-nginx-jwt-master
    container_name: nginx
    ports:
      - "80:1880"
    env_file:
      - ./opt/secrets.env
    volumes:
      - /etc/nginx/conf.d
      - ./openresty-nginx-jwt-master/bearer.lua:/bearer.lua

  dockergen:
    build: docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
  
  node-red:
    image: nodered/node-red-docker
    mem_limit: 536870912
    environment:
      - VIRTUAL_HOST=${IP}
      - VIRTUAL_PORT=1880

